### ISSUE TITLE
Support Signature in header

### ISSUE THREAD

**Issue by YassineElbouchaibi** [ComfortablyCoding/strapi-plugin-website-builder#10]
Either we add something like this in config:
```js
config: {
  ...
  secret: {
    headerKey: "X-Hub-Signature",
    hash: "sha1",
    secret: "SomeSecret", 
  },
  ...
}
```
and add something like this
```js
function createHmacSignature(req, hash, secretKey) {
  return require("crypto")
    .createHmac(hash, secretKey)
    .update(JSON.stringify(req.body))
    .digest("hex");
}
```
or have headers object accept functions
```js
config: {
  ...
  headers: {
    "X-Hub-Signature": (req) => "someValue",
  },
  ...
}
```

I will try something

**Comment by ComfortablyCoding** [comment]
Hello @YassineElbouchaibi,

I am okay with the first method. Thank you very much for the PR!

I have left some comments regarding some required changes, let me know if ny further clarification is needed.
