### ISSUE TITLE
ValidationError: url must be a valid URL (with env variable)

### ISSUE THREAD

**Issue by matepaiva** [ComfortablyCoding/strapi-plugin-website-builder#19]
Hello, first of all thank you for the amazing job!

I just want to let you know that the plugin is throwing an error (url must be a valid URL) when the URL is created using env vars. In my example:

```js
module.exports = ({ env }) => ({
  'website-builder': {
    enabled: true,
    config: {
      url: `${env('FRONTEND_URL', 'https://example.com')}/api/builder`,
      trigger: {
        type: 'event',
        events: [{
          params: ({ id, slug }, x) => ({ id, slug, model: 'article' }),
          model: 'article',
          types: ['create', 'delete', 'update'],
        }],
      },
    }
  },
});
```

Despite that, it's working fine even with the error displaying when bootstrapping the application. Thank you again!

**Comment by ComfortablyCoding** [comment]
Sounds like its failing the yup url check but is still a valid URL. Do you mind sharing the URL syntax of the FRONTEND_URL?

**Comment by matepaiva** [comment]
@ComfortablyCoding currently: `FRONTEND_URL=http://localhost:3000`

**Comment by ComfortablyCoding** [comment]
Yeah, that fails the yup url constraints. Looks like I will need to roll my own simple URL check.

**Comment by ComfortablyCoding** [comment]
A fix for this will be in the next release.

**Comment by matepaiva** [comment]
Hey @ComfortablyCoding, could you release this fix, please, if it's already done? It makes debugging and developing in general more difficult because of the error on every autorestart.

Also, I would be greatuful to know if you are going to release it soon, because if not then I will try to patch the bug with `patching-package`.

Thanks!

**Comment by ComfortablyCoding** [comment]
@matepaiva sorry about that, thought it had been released already. Added in the new 2.2.1 release.
