### ISSUE TITLE
Support configuration of multiple manual builds

### ISSUE THREAD

**Issue by Fjormos** [ComfortablyCoding/strapi-plugin-website-builder#28]
It would be nice to have the possibility of configuring multiple manual triggers, e.g. one for the production site and the other for a staging/testing site. So the website builder tab would show two buttons in this case.

**Comment by ComfortablyCoding** [comment]
Agreed, I'll look into adding this. I think a drop-down or a modal popup with all the options might be better than multiple buttons. Less clutter.

**Comment by russell-matt** [comment]
+1 for this request

I'd like to use this plugin in my project, but allowing for multiple different triggers would be a necessity. Having manual triggers for each environment, alongside an event or cron trigger for the dev site.

**Comment by ComfortablyCoding** [comment]
I'm working on implementing this in the next version.

Most of the configuration will be moved to the UI under the settings tab so you don't need to restart the server everytime.

No ETA yet.

**Comment by ctrlsio** [comment]
+1

Would be super helpful. Agreed!

**Comment by ComfortablyCoding** [comment]
Update: I will try to have this feature released over the next week or so.
