### ISSUE TITLE
Suggestion adding http responses

### ISSUE THREAD

**Issue by quiloos39** [ComfortablyCoding/strapi-plugin-website-builder#29]
I liked the idea of this plugin, but I found error messages lacking the necessary information. Is possible also include HTTP responses too, so if something goes wrong, the developer can have a better idea of where it went wrong.

also, in the documentation, I think it should be mentioned that the request we are sending is a POST request. (I initially thought it was GET request)

**Comment by ComfortablyCoding** [comment]
Thanks for the feedback and interest.

I agree that the http response should be included as well, I will look into adding this.

In regards to adding a note about it being a POST request I can do so as well. Generally build/trigger requests are via POST.
