### ISSUE TITLE
Gatsby Cloud Clearing Cache Header does not work

### ISSUE THREAD

**Issue by t-kietzmann** [ComfortablyCoding/strapi-plugin-website-builder#30]
Hey, i want to build a Gatsby Site hosted on Gatsby Cloud with a cache clear:

https://support.gatsbyjs.com/hc/en-us/articles/360053279533-How-do-I-clear-a-build-cache-

This is my config: 

` "website-builder": {
    enabled: true,
    config: {
      url: env("GATSBY_BUILD_HOOK"),
      headers: {
        "x-gatsby-cache": false,
      },
      trigger: {
        type: "manual",
      },
    },
  },`

It seems that this does not work as expected (webhook triggers, but header is not working)

**Comment by ComfortablyCoding** [comment]
How are you checking if headers are working? I tested via webhook.site and headers are being sent and received properly.

![Screenshot from 2022-11-01 20-04-52](https://user-images.githubusercontent.com/44623501/199364495-3b663bb9-fe09-495f-92d4-6b2a3943c814.png)

**Comment by t-kietzmann** [comment]
Thanks for your investigation - it seems that gatsby cloud doesn't work as expected. I had a ticket open there and they said it should work..
