### ISSUE TITLE
Not supported in newer Strapi Versions

### ISSUE THREAD

**Issue by birdzai** [ComfortablyCoding/strapi-plugin-website-builder#31]
Not supported in new Strapi versions.

Supported in Node Versions
"engines": {
"node": ">=14.19.1 <=16.x.x",
"npm": ">=6.0.0"
},

Not Supported in Latest Versions
"engines": {
"node": ">=14.19.1 <=18.x.x",
"npm": ">=6.0.0"
},

**Comment by ComfortablyCoding** [comment]
Thanks for the report, fixed in v2.2.2
