### ISSUE TITLE
Plugin not displayed in side bar.

### ISSUE THREAD

**Issue by yurivangeffen** [ComfortablyCoding/strapi-plugin-website-builder#35]
It seems that following the instructions on this plugin does not enable it properly.
I ran the `yarn` install command and created the following plugin config:

```typescript
...
config: {
  url: '<SOME URL>',
  headers: {
    "Authorization": env("TOKEN"),
  },
  trigger: {
    type: 'manual',
  },
}
...
```

I see the plugin seems registered:
<img width="1222" alt="Screenshot 2023-01-09 at 17 11 35" src="https://user-images.githubusercontent.com/4107720/211354597-db578554-4f84-4925-88e1-07af4d4dc27a.png">

But no side bar menu is displayed:
<img width="218" alt="Screenshot 2023-01-09 at 17 12 06" src="https://user-images.githubusercontent.com/4107720/211360934-e0d0b0e6-e30c-4b7a-ad29-f3ba9dc0ef67.png">

**Comment by ComfortablyCoding** [comment]
A clean build of the admin should fix that.

**Comment by yurivangeffen** [comment]
Thanks, that indeed fixes the issue! And the plugin works like a charm.
Maybe it's good to add this caveat to the documentation?

**Comment by ComfortablyCoding** [comment]
Agreed! It has been added via #36
