### ISSUE TITLE
Sorting of the build-logs

### ISSUE THREAD

**Issue by BennyMoser** [ComfortablyCoding/strapi-plugin-website-builder#45]
Probably not a big deal, but can you please change the sorting of the build logs to a descending ID. 
Because now, if you have more than 25 records, only the oldest 25 will be displayed, which makes debugging nearly impossible.

PS: thank you so much for this plugin 🙏 i really appreciate your work!

**Comment by ComfortablyCoding** [comment]
Fair point. Will see if I can push a fix for this soon.

**Comment by ComfortablyCoding** [comment]
This is fixed in v3.0.1

P.S.
You might need to do a clean build to see the changes.

**Comment by bennyhoyer** [comment]
Thanks a lot for this 🙏 Works perfectly!
