### ISSUE TITLE
headers option is ignored

### ISSUE THREAD

**Issue by descazal** [ComfortablyCoding/strapi-plugin-website-builder#6]
Hi,

Thank you for this plugin! I was waiting for it. 👍 

The headers option seems to be ignored.
I think it might be due to a typo there:
https://github.com/ComfortablyCoding/strapi-plugin-website-builder/blob/e219ddc95bd89765fe1c78014c05e53415187bc6/server/services/build-service.js#L21

It works fine after I added an 's' at `headers`.

**Comment by ComfortablyCoding** [comment]
Hello @descazal ,

thank you for catching that, it has been fixed in v2.0.2
